steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/ksp-demos/docker-ai-images/flux-dev-cr:v6dl'
    - '.'

# Step 2: Push the Docker image to the Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/ksp-demos/docker-ai-images/flux-dev-cr:v6dl'

# Specify the machine type for the build
options:
  machineType: 'E2_HIGHCPU_32'

# Specify the location of the built image in Artifact Registry
images:
- 'us-central1-docker.pkg.dev/ksp-demos/docker-ai-images/flux-dev-cr:v6dl'
